[package]
name = "luzure-winit"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true

[dependencies]
luzure-backend.workspace = true
luzure-input.workspace = true

raw-window-handle.workspace = true
winit.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
winit = { workspace = true, features = ["wayland", "wayland-csd-adwaita", "wayland-dlopen", "x11"] }

[target.'cfg(target_os = "android")'.dependencies]
winit = { workspace = true, features = ["android-game-activity"] }

[target.'cfg(target_family = "wasm")'.dependencies]
web-sys = { workspace = true, features = ["console"] }
