[package]
name = "luzure-backend"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true

[dependencies]
luzure-input.workspace = true

raw-window-handle.workspace = true
thiserror.workspace = true
