[package]
name = "luzure-thread"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true

[dependencies]
thiserror.workspace = true

[target.'cfg(target_family = "wasm")'.dependencies]
web-time.workspace = true
